/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg3.Vista;

/**
 *
 * @author Alber
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAvanzarDia = new javax.swing.JButton();
        botonCalentamientoGlobal = new javax.swing.JButton();
        botonIvasionZombie = new javax.swing.JButton();
        botonEnfriamientoGlobal = new javax.swing.JButton();

        botonAvanzarDia.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        botonAvanzarDia.setText("Avanzar dia");
        botonAvanzarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzarDiaPulsado(evt);
            }
        });

        botonCalentamientoGlobal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        botonCalentamientoGlobal.setText("Calentamiento global");
        botonCalentamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalentamientoGlobalPulsado(evt);
            }
        });

        botonIvasionZombie.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        botonIvasionZombie.setText("Invasion zombie");
        botonIvasionZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInvasionZombiePulsado(evt);
            }
        });

        botonEnfriamientoGlobal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        botonEnfriamientoGlobal.setText("Enfriamento global");
        botonEnfriamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnfriamientoGlobalPulsado(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCalentamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAvanzarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonIvasionZombie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(botonEnfriamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(botonAvanzarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botonCalentamientoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(botonEnfriamientoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonIvasionZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAvanzarDiaPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzarDiaPulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAvanzarDiaPulsado

    private void botonCalentamientoGlobalPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalentamientoGlobalPulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalentamientoGlobalPulsado

    private void botonInvasionZombiePulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInvasionZombiePulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInvasionZombiePulsado

    private void botonEnfriamientoGlobalPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnfriamientoGlobalPulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnfriamientoGlobalPulsado


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAvanzarDia;
    private javax.swing.JButton botonCalentamientoGlobal;
    private javax.swing.JButton botonEnfriamientoGlobal;
    private javax.swing.JButton botonIvasionZombie;
    // End of variables declaration//GEN-END:variables
}
