/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg3.Vista;

import java.awt.BorderLayout;
import practica.pkg3.Practica3;

public class PantallaPrincipal extends javax.swing.JFrame {
   Practica3 model;
    /**
     * Creates new form Vista1
     * @param p3
     */
    public PantallaPrincipal(Practica3 p3) {
        super("Pantalla Simulador Entorno Apolcalíptico");
        initComponents();
        //this.setLayout(new BorderLayout());
        //this.setSize(700,400);
        
        model =p3;
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BotonCalentamientoGlobal = new javax.swing.JButton();
        BotonEnfriamientoGlobal = new javax.swing.JButton();
        BotonAvanzar10Dias = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAvanzarDia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ZonaTexto = new javax.swing.JTextArea();
        BotonInvasionZombie = new javax.swing.JToggleButton();
        BotonEpidemiaGlobal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BotonSedDeSangre = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemArchivo = new javax.swing.JMenu();
        MenuItemCrearEntorno = new javax.swing.JMenuItem();
        MenuItemGuardarEntorno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuDetalles = new javax.swing.JMenu();
        MenuItemResumenEntorno = new javax.swing.JMenuItem();
        MenuItemDetallesDia = new javax.swing.JMenuItem();
        MenuItemResumenDia = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        BotonCalentamientoGlobal.setText("Calentamiento global");
        BotonCalentamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalentamientoGlobalActionPerformed(evt);
            }
        });

        BotonEnfriamientoGlobal.setText("Enfriamiento global");
        BotonEnfriamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnfriamientoGlobalActionPerformed(evt);
            }
        });

        BotonAvanzar10Dias.setText("Avanzar 10 dias");
        BotonAvanzar10Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzar10DiasActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAvanzarDia.setText("Avanzar día");
        BotonAvanzarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzarDiaActionPerformed(evt);
            }
        });

        ZonaTexto.setEditable(false);
        ZonaTexto.setColumns(20);
        ZonaTexto.setRows(5);
        jScrollPane1.setViewportView(ZonaTexto);

        BotonInvasionZombie.setText("Invasion Zombie");
        BotonInvasionZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInvasionZombieActionPerformed(evt);
            }
        });

        BotonEpidemiaGlobal.setText("Epidemia global");
        BotonEpidemiaGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEpidemiaGlobalActionPerformed(evt);
            }
        });

        jButton1.setText("Invasion Alien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BotonSedDeSangre.setText("Sed de Sangre");
        BotonSedDeSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSedDeSangreActionPerformed(evt);
            }
        });

        MenuItemArchivo.setText("Archivo");

        MenuItemCrearEntorno.setText("Crear entorno");
        MenuItemCrearEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCrearEntornoActionPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemCrearEntorno);

        MenuItemGuardarEntorno.setText("Guardar entorno");
        MenuItemGuardarEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGuardarEntornoPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemGuardarEntorno);

        jMenuBar1.add(MenuItemArchivo);
        jMenuBar1.add(jMenu2);

        MenuDetalles.setText("Detalles");

        MenuItemResumenEntorno.setText("Resumen entorno");
        MenuItemResumenEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemResumenEntornoActionPerformed(evt);
            }
        });
        MenuDetalles.add(MenuItemResumenEntorno);

        MenuItemDetallesDia.setText("Detalles del dia");
        MenuItemDetallesDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDetallesDiaActionPerformed(evt);
            }
        });
        MenuDetalles.add(MenuItemDetallesDia);

        MenuItemResumenDia.setText("Resumen dia");
        MenuItemResumenDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemResumenDiaActionPerformed(evt);
            }
        });
        MenuDetalles.add(MenuItemResumenDia);

        jMenuBar1.add(MenuDetalles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCalentamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(BotonEnfriamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAvanzar10Dias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAvanzarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEpidemiaGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonInvasionZombie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonSedDeSangre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAvanzarDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAvanzar10Dias)
                        .addGap(13, 13, 13)
                        .addComponent(BotonEpidemiaGlobal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCalentamientoGlobal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEnfriamientoGlobal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonSedDeSangre)
                        .addGap(4, 4, 4)
                        .addComponent(BotonInvasionZombie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonSalir)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemGuardarEntornoPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGuardarEntornoPulsado
        model.GuardarEstado(model.getEntorno());
    }//GEN-LAST:event_MenuItemGuardarEntornoPulsado

    private void MenuItemCrearEntornoActionPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCrearEntornoActionPulsado
        model.setEntorno(model.crearEntorno());
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_MenuItemCrearEntornoActionPulsado

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void BotonAvanzar10DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzar10DiasActionPerformed
        model.getEntorno().Avanzar10Dias();
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
       
    }//GEN-LAST:event_BotonAvanzar10DiasActionPerformed

    private void BotonCalentamientoGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalentamientoGlobalActionPerformed
        model.getEntorno().CalentamientoGlobal();
        
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_BotonCalentamientoGlobalActionPerformed

    private void BotonEnfriamientoGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnfriamientoGlobalActionPerformed
        model.getEntorno().Glaciacion();
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_BotonEnfriamientoGlobalActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        model.GuardarEstado(model.getEntorno()); 
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void MenuItemResumenEntornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemResumenEntornoActionPerformed
        ZonaTexto.setText(model.getEntorno().Resumen());
    }//GEN-LAST:event_MenuItemResumenEntornoActionPerformed

    private void BotonAvanzarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzarDiaActionPerformed
        model.getEntorno().AvanzarDia();
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_BotonAvanzarDiaActionPerformed

    private void BotonInvasionZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInvasionZombieActionPerformed
       if(BotonInvasionZombie.getModel().isSelected())
        model.getEntorno().InvasionZombie(true);
       else 
        model.getEntorno().InvasionZombie(false);   
    }//GEN-LAST:event_BotonInvasionZombieActionPerformed

    private void BotonEpidemiaGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEpidemiaGlobalActionPerformed
        model.getEntorno().EpidemiaGlobal();
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_BotonEpidemiaGlobalActionPerformed

    private void BotonSedDeSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSedDeSangreActionPerformed
         if(BotonSedDeSangre.getModel().isSelected())
        model.getEntorno().SedDeSangre(true);
       else 
        model.getEntorno().SedDeSangre(false);   
    }//GEN-LAST:event_BotonSedDeSangreActionPerformed

    private void MenuItemDetallesDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDetallesDiaActionPerformed
        ZonaTexto.setText(model.getEntorno().DetallesDiaActual());
    }//GEN-LAST:event_MenuItemDetallesDiaActionPerformed

    private void MenuItemResumenDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemResumenDiaActionPerformed
        ZonaTexto.setText(model.getEntorno().ResumenDia());
    }//GEN-LAST:event_MenuItemResumenDiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ZonaTexto.setText("\nLos Alien han invadido la tierra y resultan ser hostiles,\ntodos los humanos que quedaban vivos pasan a ser sus esclavos.\nLo sentimos, la simulación vuelve a empezar.");
        model.setEntorno(model.crearEntorno());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new PantallaPrincipal();
        JFrame.setDefaultLookAndFeelDecorated(true);
        frame.setPreferredSize(new Dimension(400, 200));
        frame.pack();
        frame.setVisible(true);*/
        
        /* Create and display the form */
      /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new PantallaPrincipal().setVisible(true);                
            }
        });*/
    //}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAvanzar10Dias;
    private javax.swing.JButton BotonAvanzarDia;
    private javax.swing.JButton BotonCalentamientoGlobal;
    private javax.swing.JButton BotonEnfriamientoGlobal;
    private javax.swing.JButton BotonEpidemiaGlobal;
    private javax.swing.JToggleButton BotonInvasionZombie;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JToggleButton BotonSedDeSangre;
    private javax.swing.JMenu MenuDetalles;
    private javax.swing.JMenu MenuItemArchivo;
    private javax.swing.JMenuItem MenuItemCrearEntorno;
    private javax.swing.JMenuItem MenuItemDetallesDia;
    private javax.swing.JMenuItem MenuItemGuardarEntorno;
    private javax.swing.JMenuItem MenuItemResumenDia;
    private javax.swing.JMenuItem MenuItemResumenEntorno;
    private javax.swing.JTextArea ZonaTexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
