/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg3.Vista;

/**
 *
 * @author Alber
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BotonAvanzarDia = new javax.swing.JToggleButton();
        BotonCalentamientoGlobal = new javax.swing.JButton();
        BotonEnfriamientoGlobal = new javax.swing.JButton();
        BotonInvasionZombie = new javax.swing.JButton();
        ZonaTexto = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemArchivo = new javax.swing.JMenu();
        MenuItemCrearEntorno = new javax.swing.JMenuItem();
        MenuItemCargarEntorno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuDetalles = new javax.swing.JMenu();
        MenuItemResumenEntorno = new javax.swing.JMenuItem();
        MenuItemDetallesDia = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        BotonAvanzarDia.setText("Avanzar dia");

        BotonCalentamientoGlobal.setText("Calentamiento global");

        BotonEnfriamientoGlobal.setText("Enfriamiento global");

        BotonInvasionZombie.setText("Invasion Zombie");

        ZonaTexto.setBackground(new java.awt.Color(255, 255, 255));
        ZonaTexto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ZonaTexto.setForeground(new java.awt.Color(0, 5, 0));
        ZonaTexto.setToolTipText("Aqui aparece la informacion que se quiera mostrar");

        javax.swing.GroupLayout ZonaTextoLayout = new javax.swing.GroupLayout(ZonaTexto);
        ZonaTexto.setLayout(ZonaTextoLayout);
        ZonaTextoLayout.setHorizontalGroup(
            ZonaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        ZonaTextoLayout.setVerticalGroup(
            ZonaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        MenuItemArchivo.setText("Archivo");

        MenuItemCrearEntorno.setText("Crear entorno");
        MenuItemCrearEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCrearEntornoActionPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemCrearEntorno);

        MenuItemCargarEntorno.setText("Cargar entorno");
        MenuItemCargarEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCargarEntornoPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemCargarEntorno);

        jMenuBar1.add(MenuItemArchivo);
        jMenuBar1.add(jMenu2);

        MenuDetalles.setText("Detalles");

        MenuItemResumenEntorno.setText("Resumen entorno");
        MenuDetalles.add(MenuItemResumenEntorno);

        MenuItemDetallesDia.setText("Detalles del dia");
        MenuDetalles.add(MenuItemDetallesDia);

        jMenuBar1.add(MenuDetalles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCalentamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAvanzarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEnfriamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonInvasionZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(ZonaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BotonAvanzarDia)
                .addGap(18, 18, 18)
                .addComponent(BotonCalentamientoGlobal)
                .addGap(45, 45, 45)
                .addComponent(BotonEnfriamientoGlobal)
                .addGap(18, 18, 18)
                .addComponent(BotonInvasionZombie)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ZonaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCargarEntornoPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCargarEntornoPulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCargarEntornoPulsado

    private void MenuItemCrearEntornoActionPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCrearEntornoActionPulsado
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCrearEntornoActionPulsado

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAvanzarDia;
    private javax.swing.JButton BotonCalentamientoGlobal;
    private javax.swing.JButton BotonEnfriamientoGlobal;
    private javax.swing.JButton BotonInvasionZombie;
    private javax.swing.JMenu MenuDetalles;
    private javax.swing.JMenu MenuItemArchivo;
    private javax.swing.JMenuItem MenuItemCargarEntorno;
    private javax.swing.JMenuItem MenuItemCrearEntorno;
    private javax.swing.JMenuItem MenuItemDetallesDia;
    private javax.swing.JMenuItem MenuItemResumenEntorno;
    private javax.swing.JPanel ZonaTexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
