/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg3.Vista;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import practica.pkg3.Practica3;

/**
 *
 * @author Alber
 */
public class PantallaPrincipal extends javax.swing.JFrame {
   Practica3 model;
    /**
     * Creates new form Vista1
     * @param p3
     */
    public PantallaPrincipal(Practica3 p3) {
        super("Hola");
        initComponents();
        this.setLayout(new BorderLayout());
        this.setSize(700,400);
        model =p3;
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BotonAvanzarDia = new javax.swing.JToggleButton();
        BotonCalentamientoGlobal = new javax.swing.JButton();
        BotonEnfriamientoGlobal = new javax.swing.JButton();
        BotonInvasionZombie = new javax.swing.JButton();
        ZonaTexto = new javax.swing.JPanel();
        BotonAvanzar10Dias = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemArchivo = new javax.swing.JMenu();
        MenuItemCrearEntorno = new javax.swing.JMenuItem();
        MenuItemGuardarEntorno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuDetalles = new javax.swing.JMenu();
        MenuItemResumenEntorno = new javax.swing.JMenuItem();
        MenuItemDetallesDia = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        BotonAvanzarDia.setText("Avanzar dia");
        BotonAvanzarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzarDiaActionPerformed(evt);
            }
        });

        BotonCalentamientoGlobal.setText("Calentamiento global");
        BotonCalentamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalentamientoGlobalActionPerformed(evt);
            }
        });

        BotonEnfriamientoGlobal.setText("Enfriamiento global");
        BotonEnfriamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnfriamientoGlobalActionPerformed(evt);
            }
        });

        BotonInvasionZombie.setText("Invasion Zombie");
        BotonInvasionZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInvasionZombieActionPerformed(evt);
            }
        });

        ZonaTexto.setBackground(new java.awt.Color(255, 255, 255));
        ZonaTexto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ZonaTexto.setForeground(new java.awt.Color(0, 5, 0));
        ZonaTexto.setToolTipText("Aqui aparece la informacion que se quiera mostrar");

        javax.swing.GroupLayout ZonaTextoLayout = new javax.swing.GroupLayout(ZonaTexto);
        ZonaTexto.setLayout(ZonaTextoLayout);
        ZonaTextoLayout.setHorizontalGroup(
            ZonaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        ZonaTextoLayout.setVerticalGroup(
            ZonaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        BotonAvanzar10Dias.setText("Avanzar 10 dias");
        BotonAvanzar10Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzar10DiasActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        MenuItemArchivo.setText("Archivo");

        MenuItemCrearEntorno.setText("Crear entorno");
        MenuItemCrearEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCrearEntornoActionPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemCrearEntorno);

        MenuItemGuardarEntorno.setText("Guardar entorno");
        MenuItemGuardarEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGuardarEntornoPulsado(evt);
            }
        });
        MenuItemArchivo.add(MenuItemGuardarEntorno);

        jMenuBar1.add(MenuItemArchivo);
        jMenuBar1.add(jMenu2);

        MenuDetalles.setText("Detalles");

        MenuItemResumenEntorno.setText("Resumen entorno");
        MenuItemResumenEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemResumenEntornoActionPerformed(evt);
            }
        });
        MenuDetalles.add(MenuItemResumenEntorno);

        MenuItemDetallesDia.setText("Detalles del dia");
        MenuDetalles.add(MenuItemDetallesDia);

        jMenuBar1.add(MenuDetalles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCalentamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAvanzarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEnfriamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonInvasionZombie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAvanzar10Dias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(ZonaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(BotonAvanzarDia)
                .addGap(18, 18, 18)
                .addComponent(BotonAvanzar10Dias)
                .addGap(18, 18, 18)
                .addComponent(BotonCalentamientoGlobal)
                .addGap(18, 18, 18)
                .addComponent(BotonEnfriamientoGlobal)
                .addGap(18, 18, 18)
                .addComponent(BotonInvasionZombie)
                .addGap(18, 18, 18)
                .addComponent(BotonSalir)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ZonaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemGuardarEntornoPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGuardarEntornoPulsado
        model.GuardarEstado(model.getEntorno());
    }//GEN-LAST:event_MenuItemGuardarEntornoPulsado

    private void MenuItemCrearEntornoActionPulsado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCrearEntornoActionPulsado
        model.setEntorno(model.crearEntorno());
    }//GEN-LAST:event_MenuItemCrearEntornoActionPulsado

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void BotonAvanzarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzarDiaActionPerformed
        model.getEntorno().AvanzarDia();
    }//GEN-LAST:event_BotonAvanzarDiaActionPerformed

    private void BotonAvanzar10DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzar10DiasActionPerformed
       model.getEntorno().Avanzar10Dias();
    }//GEN-LAST:event_BotonAvanzar10DiasActionPerformed

    private void BotonCalentamientoGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalentamientoGlobalActionPerformed
        model.getEntorno().CalentamientoGlobal();
    }//GEN-LAST:event_BotonCalentamientoGlobalActionPerformed

    private void BotonEnfriamientoGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnfriamientoGlobalActionPerformed
        model.getEntorno().Glaciacion();
    }//GEN-LAST:event_BotonEnfriamientoGlobalActionPerformed

    private void BotonInvasionZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInvasionZombieActionPerformed
        model.getEntorno().InvasionZombie();
    }//GEN-LAST:event_BotonInvasionZombieActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void MenuItemResumenEntornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemResumenEntornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemResumenEntornoActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new PantallaPrincipal();
        JFrame.setDefaultLookAndFeelDecorated(true);
        frame.setPreferredSize(new Dimension(400, 200));
        frame.pack();
        frame.setVisible(true);*/
        
        /* Create and display the form */
      /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new PantallaPrincipal().setVisible(true);                
            }
        });*/
    //}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAvanzar10Dias;
    private javax.swing.JToggleButton BotonAvanzarDia;
    private javax.swing.JButton BotonCalentamientoGlobal;
    private javax.swing.JButton BotonEnfriamientoGlobal;
    private javax.swing.JButton BotonInvasionZombie;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JMenu MenuDetalles;
    private javax.swing.JMenu MenuItemArchivo;
    private javax.swing.JMenuItem MenuItemCrearEntorno;
    private javax.swing.JMenuItem MenuItemDetallesDia;
    private javax.swing.JMenuItem MenuItemGuardarEntorno;
    private javax.swing.JMenuItem MenuItemResumenEntorno;
    private javax.swing.JPanel ZonaTexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
